// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// ⚠️  STUB FILE — FOR COMPILATION ONLY
// This file is auto-generated by snarkjs after ZK circuit setup.
// Run: npm run export:verifier
// Replace this stub with the real verifier before deploying to production!

contract Groth16Verifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[2] calldata _pubSignals
    ) external pure returns (bool) {
        // Stub: always returns true
        // Replace with snarkjs-generated verifier for production
        return true;
    }
}
